rules:
  branches:
    azure-spring-boot-sso-example:
      requireReviewCount: 3
      dismissStaleReviews: true
      requireCodeOwnerReview: true
      requireBranchUpToDate: true
      includeAdmin: true
      requireLinearHistory: true
      allowProtectedBranchDelete: true
      requiredStatusChecks: ["Trufflehog", "continuous-integration"]
      patterns:
        - '^master$'
        - '^main$'
        - '^develop$'
spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer